### PR TITLE
Disambiguate NativeAOT, and Wasm identification in BenchmarkDotNet.Po…

### PR DESCRIPTION
**Pull request by radical**
…rtability.RuntimeInformation

Fixes https://github.com/dotnet/BenchmarkDotNet/issues/2099 .

cc @adamsitnik @lewing

### CODE REVIEW

**Review by lewing — COMMENTED** [review]
I'm curious what case NativeAOT is trying to distinguish here?

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @radical !

**Comment by lewing** [comment]
I think this has broken mono aot reporting

**Comment by adamsitnik** [comment]
> there doesn't seem to be a wasm report with a label indicating it was aot'd since 9/1

@lewing  The performance repo has not updated BDN since August, so the reason for that is most likely something different.

https://github.com/dotnet/performance/blob/06fee6199750607af3484816a0456d757a4cead9/src/harness/BenchmarkDotNet.Extensions/BenchmarkDotNet.Extensions.csproj#L10-L11

**Pull request merged**
