### PR TITLE
Fix netcoreapp3.0 builds

### PR DESCRIPTION
**Pull request by timcassell**
I got the wrong version of a nuget package in #2352.

### CODE REVIEW

**Comment by AndreyAkinshin** [comment]
Why do we use different versions of `Microsoft.CodeAnalysis.CSharp` with different target frameworks? (`4.2.0`->`4.1.0` with `netstandard2.0` and `4.5.0` with `net6.0`)

**Comment by timcassell** [comment]
> Why do we use different versions of `Microsoft.CodeAnalysis.CSharp` with different target frameworks? (`4.2.0`->`4.1.0` with `netstandard2.0` and `4.5.0` with `net6.0`)

Are you suggesting we just use the older version for all targets?

**Comment by AndreyAkinshin** [comment]
Previously, we used `3.0.0` but it caused [compatibility issues](https://github.com/dotnet/BenchmarkDotNet/issues/2266) in some cases. Therefore, it was updated to [4.5.0](https://github.com/dotnet/BenchmarkDotNet/pull/2288/files) (the latest version at the moment of update).
I believe that there is no perfect version of `Microsoft.CodeAnalysis.CSharp` since it would cause problems for those who use other versions of this package that are not compatible with our target version. However, I would prefer that we use the same version across all the target frameworks.

**Review by AndreyAkinshin — APPROVED** [review]

**Comment by AndreyAkinshin** [comment]
@timcassell thanks!

**Pull request merged**
