### PR TITLE
Fix NRE in MetricColumn (#986)

### PR DESCRIPTION
**Pull request by qbit86**
Fixes NRE after unchecked access to `BenchmarkReport.Metrics` property.

### CODE REVIEW

**Comment by AndreyAkinshin** [comment]
@qbit86, thanks for the PR!

I guess it will be better to make `BenchmarkReport.Metrics` non-nullable instead of catching all the cases where we forgot to add a null check.

P.S. Also it will be nice to add a test for this case.

**Comment by qbit86** [comment]
> I guess it will be better to make `BenchmarkReport.Metrics` non-nullable instead of catching all the cases where we forgot to add a null check.

Ok, then feel free to decline this PR, I'll prepare another.

**Comment by AndreyAkinshin** [comment]
> Ok, then feel free to decline this PR, I'll prepare another.

@qbit86 you can use the same PR. Just add relevant commits yo your master branch.

**Comment by qbit86** [comment]
> Also it will be nice to add a test for this case.

I narrowed down the [repro benchmark](https://github.com/qbit86/spontaneous-benchmark/blob/a2a2ff1689a6d2364f87fbe8a95c00aac0879286/benchmarks/Spontaneous.LanguageBenchmarks/BdnMetricsNreRepro.cs), but I don't know where to place it, in which test to run it, how to specify expected result vs. actual, etc.

**Comment by qbit86** [comment]
...But at least existing checks have passed with no regression on CI.

**Comment by AndreyAkinshin** [comment]
@qbit86 the best option is a unit test in the `BenchmarkDotNet.Tests` project. You can find some good examples in the `Reports` folders.
If it's not possible, we can introduce another integration test in the `BenchmarkDotNet.IntegrationTests` project (check out usages of BenchmarkTestExecutor). However, we are trying to not introduce additional integration tests (if it's possible) because they take too much time.

**Comment by qbit86** [comment]
@AndreyAkinshin
> we are trying to not introduce additional integration tests (if it's possible) because they take too much time.

I guess, indeed, the very essence of this issue can be isolated from actual benchmark running.

> the best option is a unit test in the `BenchmarkDotNet.Tests` project. You can find some good examples in the `Reports` folders.

I believe this belongs to `Summary` tests, since it is `Summary` ctor in the middle of the stack trace who suffers more from passed null, not `BenchmarkReport` itself.

I've added `SummaryTests` class to `Reports/` folder and checked that test fails on old version of code and passes on fixed version.

**Comment by qbit86** [comment]
@AndreyAkinshin 

> I can't reproduce the failure.
> If I revert both changes (in `BenchmarkReport` and `DefaultColumnProviders`), the test is still green.

To which commit did you try to revert changes? It may not reproduce since I've actually fixed the issue twice — once with naive approach of null-checking on call-site, then reverted it and add principal fix making property non-nullable. So it won't reproduce if you only revert last changes.

**Comment by qbit86** [comment]
@AndreyAkinshin 
> I can't reproduce the failure.

Ok, I'll try to make the test red again :)

**Comment by AndreyAkinshin** [comment]
@qbit86 thanks, merged.

**Pull request merged**
