### PR TITLE
Add ValidateExecutableReferencesMatchSelfContained

### PR DESCRIPTION
**Pull request by kant2002**
This is required to make CoreRT work on 5.0.300 SDK

### CODE REVIEW

**Comment by adamsitnik** [comment]
@MichalStrehovsky could you please confirm that?

**Comment by MichalStrehovsky** [comment]
If we can't compile with the .NET 5 SDK without this, the fix should probably go to the NativeAOT branch instead.

**Comment by kant2002** [comment]
I create this PR because I find #1707. Isn't this means that same logic applied to Mono AOT?

**Comment by adamsitnik** [comment]
#1707 was specific to Mono AOT. 

We have a [test](https://github.com/dotnet/BenchmarkDotNet/blob/63e28c100a42a6492d09a0b93a8a4c141061bb0d/tests/BenchmarkDotNet.IntegrationTests/CoreRtTests.cs#L17) that ensures that we support latest CoreRT version and our CI is green, which means that this change is not needed.

**Pull request closed without merging**
