### PR TITLE
Arguments

### PR DESCRIPTION
**Pull request by adamsitnik**
This is initial implementation of `[Arguments]` and `[ArgumentsSource]` attributes, which allows our users to define benchmarks with parameters #256 

- [x]  allow to define compile time constant arguments for method with simple `[Arguments]` attribute
- [x]  allow to define arguments source with `[ArgumentsSource]` attribute
- [x]  support `IParam` for more complex types
- [x]  possibility to use `[Params]` and `[Arguments]` within same benchmark
- [x]  minimal overhead
- [x]  `ref` and `out` parameters support
- [x]  `InProcessToolchain` support (now only warning, issue reported #687)
- [x]  docs
- [x]  samples
- [x]  Disassembler support (so far we assumed that benchmarks were always parameterless)

@AndreyAkinshin how it works:

1. I define new **field** in `Runnable` for every argument
2. I initialize the fields in the ctor of `Runnable` to avoid any creation overhead (like allocating heap memory)
3. Each delegate accepts a list of arugments now. The declaration of Idle and Main is the same in terms of arguments.
4. In `MultiAction` I just load the fields to local variables before running the loop. In the loop I just pass the local variables as arguments.

@AndreyAkinshin  If you like it too I am going to implement InProcessToolchain support and write the docs. If you don't I am going to improve it first to meet your requirements.

Sample:

```cs
public class IntroArguments
{
    [Params(true, false)] // Arguments can be combined with Params
    public bool AddExtra5Miliseconds;

    [Benchmark]
    [Arguments(100, 10)]
    [Arguments(100, 20)]
    [Arguments(200, 10)]
    [Arguments(200, 20)]
    public void Benchmark(int a, int b)
    {
        if (AddExtra5Miliseconds)
            Thread.Sleep(a + b + 5);
        else
            Thread.Sleep(a + b);
    }
}
```

|    Method | AddExtra5Miliseconds |   a |  b |     Mean |     Error |    StdDev |
|---------- |--------------------- |---- |--- |---------:|----------:|----------:|
| **Benchmark** |                **False** | **100** | **10** | **110.4 ms** | **0.0983 ms** | **0.0919 ms** |
| **Benchmark** |                **False** | **100** | **20** | **120.5 ms** | **0.0672 ms** | **0.0629 ms** |
| **Benchmark** |                **False** | **200** | **10** | **210.4 ms** | **0.1380 ms** | **0.1291 ms** |
| **Benchmark** |                **False** | **200** | **20** | **220.2 ms** | **0.0430 ms** | **0.0381 ms** |
| **Benchmark** |                 **True** | **100** | **10** | **115.1 ms** | **0.0034 ms** | **0.0026 ms** |
| **Benchmark** |                 **True** | **100** | **20** | **125.1 ms** | **0.0040 ms** | **0.0036 ms** |
| **Benchmark** |                 **True** | **200** | **10** | **215.2 ms** | **0.0038 ms** | **0.0034 ms** |
| **Benchmark** |                 **True** | **200** | **20** | **225.2 ms** | **0.0186 ms** | **0.0165 ms** |

```cs
public class IntroArgumentsSource
{
    [Benchmark]
    [ArgumentsSource(nameof(Numbers))]
    public double Pow(double x, double y) => Math.Pow(x, y);

    public IEnumerable<object[]> Numbers()
    {
        yield return new object[] { 1.0, 1.0 };
        yield return new object[] { 2.0, 2.0 };
        yield return new object[] { 4.0, 4.0 };
        yield return new object[] { 10.0, 10.0 };
    }
}
```

| Method |  x |  y |      Mean |     Error |    StdDev |
|------- |--- |--- |----------:|----------:|----------:|
|    **Pow** |  **1** |  **1** |  **9.360 ns** | **0.0190 ns** | **0.0149 ns** |
|    **Pow** |  **2** |  **2** | **40.624 ns** | **0.3413 ns** | **0.3192 ns** |
|    **Pow** |  **4** |  **4** | **40.537 ns** | **0.0560 ns** | **0.0524 ns** |
|    **Pow** | **10** | **10** | **40.395 ns** | **0.3274 ns** | **0.3063 ns** |

```cs
[MemoryDiagnoser]
public class IntroArrayParam
{
    [Benchmark]
    [ArgumentsSource(nameof(Data))]
    public int ArrayIndexOf(int[] array, int value) => Array.IndexOf(array, value);

    [Benchmark]
    [ArgumentsSource(nameof(Data))]
    public int ManualIndexOf(int[] array, int value)
    {
        for (int i = 0; i < array.Length; i++)
            if (array[i] == value)
                return i;

        return -1;
    }

    public IEnumerable<object[]> Data()
    {
        yield return new object[] { ArrayParam<int>.ForPrimitives(new[] { 1, 2, 3 }), 4 };
        yield return new object[] { ArrayParam<int>.ForPrimitives(Enumerable.Range(0, 100).ToArray()), 4 };
        yield return new object[] { ArrayParam<int>.ForPrimitives(Enumerable.Range(0, 100).ToArray()), 101 };
    }
}
```

|        Method |      array | value |      Mean |     Error |    StdDev | Allocated |
|-------------- |----------- |------ |----------:|----------:|----------:|----------:|
|  **ArrayIndexOf** | **Array[100]** |     **4** | **15.558 ns** | **0.0638 ns** | **0.0597 ns** |       **0 B** |
| ManualIndexOf | Array[100] |     4 |  5.345 ns | 0.0668 ns | 0.0625 ns |       0 B |
|  **ArrayIndexOf** |   **Array[3]** |     **4** | **14.334 ns** | **0.1758 ns** | **0.1558 ns** |       **0 B** |
| ManualIndexOf |   Array[3] |     4 |  2.758 ns | 0.0905 ns | 0.1208 ns |       0 B |
|  **ArrayIndexOf** | **Array[100]** |   **101** | **78.359 ns** | **1.8853 ns** | **2.0955 ns** |       **0 B** |
| ManualIndexOf | Array[100] |   101 | 80.421 ns | 0.6391 ns | 0.5978 ns |       0 B |

### CODE REVIEW

**Comment by ig-sinicyn** [comment]
@adamsitnik 
Will update the `InProcessToolchain` if you want.
I did not track recent changes in BDN. Is there something else that need to be ported to the inprocess runner too?

**Comment by AndreyAkinshin** [comment]
@adamsitnik, it looks great!
I'm at a conference right now, will review it tomorrow.

**Comment by adamsitnik** [comment]
@ig-sinicyn do you have time for this? It would be great! I am not sure if the new Interation Setup/Cleanup works with InProcessToolchain

@AndreyAkinshin great, see you in Moscow ;)

**Comment by ig-sinicyn** [comment]
@adamsitnik 
> do you have time for this?

Yeah. I'm going to look for the ways it will be implemented and then will create a issue for it. After confirmed I'll push my changes into this branch.
Are you ok with T4-generated code? If not we will had to throw a `NotSupportedException` for method with args that will be called with `BenchmarkActionCodegen.DelegateCombine` set.

**Comment by adamsitnik** [comment]
> Are you ok with T4-generated code?

what do you mean by that?

**Comment by ig-sinicyn** [comment]
>what do you mean by that?

As far as I can see the only way to pass args to the target method is to generate a closure class for each  delegate (Action<T1...TN> and Func<T1..TN>).

It cant be done by Reflection.Emit if the `BenchmarkActionCodegen.DelegateCombine` mode set. This mode is used for environments such as UWP or .Net Native that do not support dynamic code emitting.

So, the only option left is to add a T4 template that will generate a set of closure classes.

**Comment by adamsitnik** [comment]
@ig-sinicyn thanks for the explanation. It sounds good to me!

**Comment by AndreyAkinshin** [comment]
@ig-sinicyn please, could we solve it somehow without T4? These templates are usually hard to maintain and I'm not sure that it will work fine on .NET Core.

**Comment by ig-sinicyn** [comment]
@AndreyAkinshin I'm very sorry, didn't look at this yet. Got unexpected deadline on my job. Will look and post a new issue with more detail on next week.

**Comment by adamsitnik** [comment]
@ig-sinicyn it looks like @AndreyAkinshin is [fine](https://github.com/dotnet/BenchmarkDotNet/issues/616#issuecomment-356379823) with the implementation for standard toolchain. Would you have some time to implement it for InProcessToolchain?

I need to update the branch and implement the disassembler change

**Comment by ig-sinicyn** [comment]
@adamsitnik 
Hi and sorry for delay, was kinda out of service:)

Will try to do something with it in a day or two.

**Comment by adamsitnik** [comment]
@ig-sinicyn great!

btw. the InProcessToolchain is very popular amongst CoreCLR and CoreFX contributors. Your idea is very succesful.

**Comment by ig-sinicyn** [comment]
@adamsitnik 
Hello and sorry-sorry-sorry for huge delay. I still have no free time at all but at weekend I did a prototype that emits code that closely matches to the code of `program.txt`. Hope to do a PR in a week or two.

**Comment by adamsitnik** [comment]
@ig-sinicyn don't worry! I can imagine that this change is not simple and it's very time-consuming.

For now, I will add a validator with an error message for those who will try arguments with `InProc`.

After this, I am going to merge this PR. I have a lot of changes coming to BDN and I need to merge it now, otherwise, I will never do that and die trying solving merge conflicts ;p

**Pull request merged**
