### PR TITLE
Fix build to align with refactoring

### PR DESCRIPTION
**Pull request by zabulus**
This PR fixes integration building and running.

### CODE REVIEW

**Comment by zabulus** [comment]
cc @adamsitnik

**Comment by zabulus** [comment]
This fixes build of uap runtime, still exception is thrown while running sample app:
```
 	[External Code]	
 	System.Private.CoreLib.dll!System.Lazy<T>.CreateValue() Line 413	C#
 	System.Private.CoreLib.dll!System.Lazy<T>.LazyInitValue() Line 358	C#
 	BenchmarkDotNet.Runtime.dll!BenchmarkDotNet.Environments.BenchmarkEnvironmentInfo.BenchmarkEnvironmentInfo()	C#
>	BenchmarkDotNet.Autogenerated.exe!BenchmarkDotNet.Autogenerated.Runnable.Run(BenchmarkDotNet.Engines.IHost host) Line 140	C#
 	[External Code]	
 	BenchmarkDotNet.Autogenerated.exe!BenchmarkDotNet.Autogenerated.App..ctor.AnonymousMethod__0() Line 90	C#
 	[External Code]	
```

```
System.NullReferenceException occurred
  HResult=0x80004003
  Message=Arg_NullReferenceException
  Source=<unknown>
  StackTrace:
   at BenchmarkDotNet.Portability.ServicesProvider.ReadProperty[TType,TProperty](TType instance, String propertyName)
   at BenchmarkDotNet.Portability.ServicesProvider.Load()
   at System.Func`1.InvokeOpenStaticThunk()
   at System.Func`1.Invoke()
   at System.Lazy`1.CreateValue() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Lazy.cs:line 413
   at System.Lazy`1.LazyInitValue() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Lazy.cs:line 358
   at BenchmarkDotNet.Environments.BenchmarkEnvironmentInfo..ctor()
   at BenchmarkDotNet.Autogenerated.Runnable.Run(IHost host) in D:\Workshop\BenchmarkDotNet\samples\BenchmarkDotNet.Samples.Uap\bin\Release\net46\Framework_DateTime_NowLatency_IntegrationTestJob\App.xaml.cs:line 140
   at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetVI[T0](Object thisPtr, IntPtr methodToCall, ArgSetupState& argSetupState, Boolean targetIsThisCall)
   at System.InvokeUtils.CallIHelperStaticCallWithInstantiation(Object thisPtr, IntPtr methodToCall, IntPtr dynamicInvokeHelperMethod, ArgSetupState& argSetupState, Boolean isTargetThisCall, IntPtr dynamicInvokeHelperGenericDictionary)
   at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object defaultParametersContext, Object[] parameters, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\InvokeUtils.cs:line 309
```

**Comment by zabulus** [comment]
Also I see following warnings:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		ILTransform : warning ILT0005: Type 'System.Diagnostics.ProcessStartInfo' was not included in compilation, but was referenced in method 'DotNetCliCommandExecutor.BuildStartInfo(string, string)'. There may have been a missing assembly.	UapBenchmarkProject			
Warning		ILTransform : warning ILT0003: Method 'DotNetCliCommandExecutor.BuildStartInfo(string, string)' will always throw an exception due to the missing method 'ProcessStartInfo..ctor()'. There may have been a missing assembly.	UapBenchmarkProject			
Warning		ILTransform : warning ILT0003: Method 'DotNetCliCommandExecutor.GetDotNetCliVersion()' will always throw an exception due to the missing method 'Process..ctor()'. There may have been a missing assembly.	UapBenchmarkProject			
Warning		ILTransform : warning ILT0005: Type 'System.Diagnostics.Process' was not included in compilation, but was referenced in method 'DotNetCliCommandExecutor.GetDotNetCliVersion()'. There may have been a missing assembly.	UapBenchmarkProject			
```
Do you need DotNetCliCommandExecutor in BDN.Runtime package?

**Comment by zabulus** [comment]
Loading of ServicesProviderContract itself is dependent on ```typeInfo.Assembly.ReadProperty<Assembly, string>("Location");``` moreover, even if assembly location is available, I have doubts that  DirectoryInfo.EnumerateFileSystemInfos finishes successfully regarding filesystem isolation of UWP applications.

**Comment by adamsitnik** [comment]
@zabulus great!

> Loading of ServicesProviderContract itself is dependent on typeInfo.Assembly.ReadProperty<Assembly, string>("Location");

Ok, that is what I was afraid of. I will provide a helper method (that will just initialize the right things in deterministic way in the beginning of the auto-generated app)

**Comment by adamsitnik** [comment]
> Do you need DotNetCliCommandExecutor in BDN.Runtime package?

I guess/hope that the methods that you get warnings for will never be invoked at runtime for Uap Toolchain.

**Pull request merged**
