### PR TITLE
Update Build Tools to use .NET Core SDK to 3.0.100

### LINKED ISSUE #1254: Update Build Tools to use .NET Core SDK to 3.0.100

### PR DESCRIPTION
**Pull request by CodeTherapist**
closes #1254 
required for #1253

### CODE REVIEW

**Comment by Ky7m** [comment]
@CodeTherapist, please update SDK for non-windows builds as well https://github.com/dotnet/BenchmarkDotNet/blob/master/build.sh#L50
I am going to improve this experience in the future, as result we won't need to update this in different places

**Comment by CodeTherapist** [comment]
@Ky7m :worried: I forgot that to check - thanks for your help.
Wouldn't it be possible to execute build.ps1 for both using powershell core?

**Comment by Ky7m** [comment]
It is possible but powershell core should be installed and it requires additional steps in CI scripts

**Comment by CodeTherapist** [comment]
@Ky7m Sure, PR update follows today.

**Comment by adamsitnik** [comment]
I am going to close and reopen it to force the Travis to re-run the tests

**Comment by adamsitnik** [comment]
There is some stupid bug that only mine and Andrey's PRs are run using Azure DevOps.

I've changed the base branch of this PR to `netCore30SDK` branch. Now I am going to merge it and open PR from `netCore30SDK` to master to run AzDO as well...

**Pull request merged**
