### PR TITLE
Task add style cope and fxcop analyzers

### PR DESCRIPTION
**Pull request by WojciechNagorski**
In this PR I added StyleCop and FxCop packages for every project in the solution.

In `CodingStyle.ruleset` file you can find configuration based on `dotnet/corefx` repo: https://github.com/dotnet/corefx/blob/06007cdedee9cfb096d884016a99e3a64bdccb45/src/Common/src/CoreLib/CodeAnalysis.ruleset
I've removed some line. Please validate this list before merge. 

There you can find similar `props` file from `dotnet/corefx`: https://github.com/dotnet/corefx/blob/3d37c15b43be2a36de5dc7f9076584407b430175/eng/Analyzers.props

PR for Hacktoberfest 😄

### CODE REVIEW

**Comment by adamsitnik** [comment]
Wojciech how many warnings do you get when you perform a clean build of the solution with all these rules enabled?

**Comment by wojtpl2** [comment]
@adamsitnik 
- With trailing whitespaces 1963
image
- Without trailing whitespaces from #1259 only 634: 
image

There is a lot of SA1000 https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1000.md
image

If you decide to clean the code, I can make one bulk PR for simple rules in no time.

**Comment by adamsitnik** [comment]
@AndreyAkinshin I like the concept of having some static code analysis, are you ok with adding StyleCop and FxCop?

**Comment by WojciechNagorski** [comment]
Is there any update on this topic? Should I improve something?

**Comment by adamsitnik** [comment]
@AndreyAkinshin ping

**Comment by WojciechNagorski** [comment]
@AndreyAkinshin ping

**Comment by AndreyAkinshin** [comment]
@WojciechNagorski thanks!

**Comment by AndreyAkinshin** [comment]
@WojciechNagorski it seems that one of our integration tests (`UserCanSpecifyCustomBuildConfiguration`) is red after the merge, see https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/history
Could you please take a look?

**Comment by WojciechNagorski** [comment]
Ok no problem. I will take a look tomorrow.

**Pull request merged**
