### PR TITLE
Fix invalid pre-requisites NativeAOT link in the 0.13.2 changelog

### LINKED ISSUE #2103: Invalid NativeAOT link in the 0.13.2 changelog
[Pre-requisites](https://github.com/dotnet/BenchmarkDotNet/blob/8514b239fea5939f888df2f976d4763a978b5784/docs/_changelog/header/v0.13.2.md?plain=1#L59) link does not work

### PR DESCRIPTION
**Pull request by KeterSCP**
Closes #2103

### CODE REVIEW

**Comment by adamsitnik** [comment]
@KeterSCP Could you please update https://github.com/dotnet/BenchmarkDotNet/blob/8514b239fea5939f888df2f976d4763a978b5784//docs/articles/configs/toolchains.md?plain=1#L198 as well?

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/BenchmarkDotNet?pullRequest=2104) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/BenchmarkDotNet?pullRequest=2104) before we can accept your contribution.<br/><br/>:x: KeterSCP [sign now](https://cla.dotnetfoundation.org/dotnet/BenchmarkDotNet?pullRequest=2104)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/BenchmarkDotNet?pullRequest=2104) it.</sub>

**Review by adamsitnik — APPROVED** [review]
LGTM, dzieki @KeterSCP !

**Comment by KeterSCP** [comment]
Dzięki za pomoc! @adamsitnik

**Comment by YegorStepanov** [comment]
Is the site only updated when a new version of BDN is released?

**Comment by adamsitnik** [comment]
> Is the site only updated when a new version of BDN is released?

Yes. I would like to release 0.13.3 soon (within than a month).

**Comment by YegorStepanov** [comment]
Can the site be updated with every commit? Should I try to fix this?

Don't publish today please, I will send some small fixes.

**Comment by KeterSCP** [comment]
>Can the site be updated with every commit?

It would be wise to update webpage only if related files changed (changes to any file inside the `docs` folder)

**Comment by adamsitnik** [comment]
> Can the site be updated with every commit? Should I try to fix this?

> It would be wise to update webpage only if related files changed (changes to any file inside the docs folder)

@AndreyAkinshin maintains this process. @AndreyAkinshin would that be possible?

**Comment by AndreyAkinshin** [comment]
Currently, https://benchmarkdotnet.org/ always describes the latest stable version of BenchmarkDotNet; docs in the master branch describe the nightly version. Therefore, it's tricky to organize the process of automatic documentation updates if we want to have the latest *stable* docs published.
I guess, the best solution is to introduce version switcher in the header of the website (e.g., `nightlight`, `v0.13.2`, `v0.13.1`, etc.), but it's hard to implement using docfx2.
Meanwhile, I can manually update the docs on special occasions since the manual process allows to control that no nightly features docs are published.

**Comment by YegorStepanov** [comment]
Is it possible to bind site update to a tag? For example, to update a dead link, you need to add a released tag (v0.13.2) to the PR? Aka backporting.

The last update came out 1.5 years later, which is a lot.

**Comment by AndreyAkinshin** [comment]
> Is it possible to bind site update to a tag? For example, to update a dead link, you need to add a released tag (v0.13.2) to the PR? Aka backporting.

It would be also quite tricky to implement since automatic cherry-picks/merges always lead to conflicts.
What we can do is a separate branch for the "stable" docs. So, if we want to backport some of the documentation fixes, we can just cherry-pick them to this branch. Since this branch is supposed to be manually updated, we can setup an automatic workflow for documentation updates.
@adamsitnik what do you think?

> The last update came out 1.5 years later, which is a lot.

Yeah, it's a separate issue. In the scope of v0.13.2, there were too many important fixes for .NET 7 support that we wanted to finished before the release. I really hope that we will be able to increase the frequency of the future updates.

**Comment by AndreyAkinshin** [comment]
It's done! Now we have the `docs-stable` branch. If we want to publish any updates to https://benchmarkdotnet.org/, we shouldn't wait for the next release. It's enough to just cherry-pick the relevant commits to `docs-stable`; the documentation from this branch will be automatically deployed to https://benchmarkdotnet.org/ via the [docs-stable workflow](https://github.com/dotnet/BenchmarkDotNet/actions/workflows/docs-stable.yaml). I just cherry-picked the commit from this PR to `docs-stable`; the fix is already [deployed](https://github.com/dotnet/BenchmarkDotNet/actions/runs/3167626786).
/cc @adamsitnik

**Pull request merged**
