### PR TITLE
Added workaround to fix incorrect CPU info when using wmic

### LINKED ISSUE #1144: Incorrect CPU info for .NET Core applications
Due to [a bug in wmic](https://aka.ms/AA51dwb) BenchmarkDotNet incorrectly reports CPU information on multi socket machines. For example, I'm expecting to get `Intel Xeon CPU E5-2687W 0 3.10GHz, 2 CPU, 32 logical and 16 physical cores`, but getting `Intel Xeon CPU E5-2687W 0 3.10GHz, 1 CPU, 16 logical and 16 physical cores`. To fix this the `?` quantifier must be replaced by `*` in the following line:

https://github.com/dotnet/BenchmarkDotNet/blob/40901c154e1a545536950ed372e6d5004731afc0/src/BenchmarkDotNet/Helpers/SectionsHelper.cs#L31

By the way, the next two lines could be removed in the future because another bug in Core FX was fixed some time ago (see dotnet/corefx#35694):

https://github.com/dotnet/BenchmarkDotNet/blob/f9c8cc5b835a3635adf1606440f10873015f5058/src/BenchmarkDotNet/Portability/RuntimeInformation.cs#L112-L113

### PR DESCRIPTION
**Pull request by YohDeadfall**
Fixes #1144.

### CODE REVIEW

**Comment by AndreyAkinshin** [comment]
@YohDeadfall thanks for the PR! Could you please add a test which verifies that BenchmarkDotNet correctly parse wmic output for multi socket machines?

**Comment by YohDeadfall** [comment]
You already have it:

https://github.com/dotnet/BenchmarkDotNet/blob/40901c154e1a545536950ed372e6d5004731afc0/tests/BenchmarkDotNet.Tests/Portability/Cpu/WmicCpuInfoParserTests.cs#L32-L54

Probably the bug in wmic doesn't exists in Windows in your test environment.

**Comment by AndreyAkinshin** [comment]
@YohDeadfall the new test has to verify that we correctly parse the wmic output (with `\r\r\n` at the end of each line). We can rewrite the existed test in the following way:
```
const string wmicNewLine = "\r\r\n";

string cpuInfo = string.Join(wmicNewLine, new string[]
{
    "",
    "",
    "MaxClockSpeed=2400",
    "Name=Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz",
    "NumberOfCores=8",
    "NumberOfLogicalProcessors=16",
    "",
    "",
    "MaxClockSpeed=2400",
    "Name=Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz",
    "NumberOfCores=8",
    "NumberOfLogicalProcessors=16"
});
```
It's an environment-independent way to verify the regex. It will prevent other developers from spoiling it.
Also, it would be nice to add a comment in `ParseSections` near the regex which explains that `\r\r\n` is a valid new line separator for `wmic` in our case.
By they way, I can't open your link from #1144 (https://aka.ms/AA51dwb), but I found a few StackOverflow questions which are related to this problem:
* [Why am I getting \r\r\n (CR CR LF) from a Windows command line in Java?](https://stackoverflow.com/q/48983566/184842)
* [How to correct variable overwriting misbehavior when parsing output](https://stackoverflow.com/q/24961755/184842)

**Comment by YohDeadfall** [comment]
> By they way, I can't open your link from #1144 (https://aka.ms/AA51dwb)

It requires Feedback Hub installed from Windows Store. This application is used to report bugs, publish suggestions, or get announcements (: I told @adamsitnik about the issue at the last DotNetos, but it took a long time to file it to Microsoft and post workaround here.

The full link is https://insider.windows.com/en-us/fb/?contextid=156&feedbackid=40b06e8e-bf61-4785-b91b-ea0658430447&form=1&utm_source=product-placement&utm_medium=feedback-hub&utm_campaign=feedback-hub-redirect.

**Comment by AndreyAkinshin** [comment]
@YohDeadfall thanks!

**Pull request merged**
