### PR TITLE
Improve restore, build and publish projects - Fix for #1002

### PR DESCRIPTION
**Pull request by wojtpl2**
After this changes `benchmarks_ci.py` works good.:

```ini
[2019/01/11 14:16:15][INFO] $ pushd "C:\Work\performance\src\benchmarks\micro"
[2019/01/11 14:16:15][INFO] $ dotnet run --project MicroBenchmarks.csproj --configuration Release --framework netcoreapp3.0 --no-restore --no-build -- --coreRun C:\Work\corefx\artifacts\bin\testhost\netcoreapp-Windows_NT-Debug-x64\shared\Microsoft.NETCore.App\9.9.9\CoreRun.exe --filter *.Perf_Dictionary.* --join --packages C:\Work\performance\artifacts\packages --runtimes netcoreapp3.0
[2019/01/11 14:16:24][INFO] // Validating benchmarks:
[2019/01/11 14:16:25][INFO] // ***** BenchmarkRunner: Start   *****
[2019/01/11 14:16:25][INFO] // ***** Building 1 exe(s) in Parallel: Start   *****
[2019/01/11 14:16:29][INFO] // start dotnet restore --packages "C:\Work\performance\artifacts\packages"  /p:UseSharedCompilation=false in C:\Work\performance\artifacts\bin\MicroBenchmarks\Release\netcoreapp3.0\3148b284-3041-4f20-a315-4811137f804d
[2019/01/11 14:16:33][INFO] // command took 3.68s and exited with 0
[2019/01/11 14:16:33][INFO] // start dotnet build -c Release  --no-restore /p:UseSharedCompilation=false in C:\Work\performance\artifacts\bin\MicroBenchmarks\Release\netcoreapp3.0\3148b284-3041-4f20-a315-4811137f804d
[2019/01/11 14:16:39][INFO] // command took 6.18s and exited with 0
[2019/01/11 14:16:39][INFO] // start dotnet publish -c Release  --no-build --no-restore /p:UseSharedCompilation=false in C:\Work\performance\artifacts\bin\MicroBenchmarks\Release\netcoreapp3.0\3148b284-3041-4f20-a315-4811137f804d
[2019/01/11 14:16:41][INFO] // command took 2.73s and exited with 0
```

In this PR I've changed:
1. CoreRunGenerator didn't support custom package directory from `--packages` parameter.
2. Now BND compile project like `benchmarks_ci.py` script in steps:
   * dotnet restore Project.csproj --packages ABC (package is add when ABC is not null)
   * dotnet build Project.csproj --no-restore (project was built in step above)
   * dotnet publish Project.csproj --no-build --no-restore (project was built and restored in steps above)

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
Disclamer: I don't know BDN internals so what I say could be meaningless, sorry in advance.

> CoreRunGenerator didn't support custom package directory from --packages parameter.

Understood.

> Now BND compile project like benchmarks_ci.py script in steps:

Is it ok build with `--no-restore --no-build` also if `run` doesn't use it?I mean could be cases where this lead to issue?
I mean it's perfect for py perf script...but for other cases?

**Comment by wojtpl2** [comment]
I've **build** with `--no-restore` and **publish** with `--no-restore` and `--no-build`.

**Comment by MarcoRossignoli** [comment]
> I've build with --no-restore and publish with --no-restore and --no-build.

Ok understood. If you try without `--no-restore --no-build` and `--packages` on `run` it's ok?

**Comment by MarcoRossignoli** [comment]
@wojtpl2 thank's!

**Comment by adamsitnik** [comment]
@jorive is gonna like this ;)

**Pull request merged**
