### PR TITLE
Return value validator

### LINKED ISSUE #136: [Feature request] Fastcheck for correctness of benchmark implementations?
Use case: prevent users from comparing methods that do different things.

It's very easy to leave bug unnoticed in one of the benchmark methods. I just did it and had to spent some time to find that one of the competitors was exiting in the middle. 

Proposed solution is fragile, does not _proofs_ that all code is correct but it's still better than nothing.
**So, the proposal:**

If benchmark method has a return value, collect it and check that all another non-void methods return the same value. The value serves as a checksum, so, if it differs benchmark should fail.
Ensuring that result of the benchmark is calculated correctly and that the result does not produce false positives is responsibility of the author of the benchmark.

I think that this has to be opt-in feature and it's enough to check the results only on first run.

### PR DESCRIPTION
**Pull request by ltrzesniewski**
This PR basically fixes #136. The use case is described there. I got tired of writing additional validation logic every time I wrote a benchmark.

It adds a `ReturnValueValidator` class which checks that benchmark methods return the same values for a given parameter set. Void methods are allowed.

It also adds `ExecutionValidatorAttribute` and `ReturnValueValidatorAttribute` for convenience.

### CODE REVIEW

**Comment by adamsitnik** [comment]
@ltrzesniewski could you also add tests for some collections (ie: array, dictionary) and custom types implementing `IEqutable`?

**Comment by adamsitnik** [comment]
@ltrzesniewski really good job! 👍 thanks for doing this!

**Comment by ltrzesniewski** [comment]
Thanks! 👍
I totally forgot about collection types, these won't compare as equal right now. I'll fix that.

**Comment by ltrzesniewski** [comment]
@adamsitnik I added a custom equality comparison logic which should be quite similar in behavior to what unit test framework equality assertions usually do, but without going as far. I preferred to optimize for simplicity. 😄 

Also, I noticed that `ExecutionValidator` always printed the generic `TargetInvocationException` message, so I fixed that as well.

**Pull request merged**
