### PR TITLE
Task remove trailing whitespace

### PR DESCRIPTION
**Pull request by wojtpl2**
In this PR I remove all trailing whitespace in the solution. 
There is a documentation for this StyleCop rule: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1028.md

I will understand if this PR is rejected.

PR for Hacktoberfest 😄

### CODE REVIEW

**Comment by adamsitnik** [comment]
Are you sure that you want to be on a git blame for every line in the project? ;P

@AndreyAkinshin what do you think?

**Comment by wojtpl2** [comment]
Only 
image

I am aware of the problems: Incorrect blame, merge in PRs. 
If this PR is rejected, I can disable SA1028 rule.

**Comment by AndreyAkinshin** [comment]
LGTM.
@wojtpl2 could you please resolve the conflicts with the master branch?

**Comment by wojtpl2** [comment]
I've resolved the conflicts. And I removed additional trailing whitespaces.

**Pull request merged**
