### PR TITLE
Cake (C# Make) integration. Migration from custom build scripts.

### LINKED ISSUE #426: [WIP] Proposal: Migrate from custom build scripts to Cake (C# Make)
[Cake (C# Make)](http://cakebuild.net/) is a cross platform build automation system with a C# DSL to do things like compiling code, copy files/folders, running unit tests, compress files and build NuGet packages.
I can help migrate from custom build scripts to CakeBuild. 

**Does it make sense?**

A few examples of real usage:
- [IdentityServer4](https://github.com/IdentityServer/IdentityServer4/blob/dev/build.cake)
- [Polly](https://github.com/App-vNext/Polly/blob/master/build.cake)

### PR DESCRIPTION
**Pull request by Ky7m**
This PR closes #426. 
It allows to build application on Windows and non-Windows platforms, tested on:

- Windows
- Ubuntu
- macOS

Each build contains next steps (with some platform specifics):

- Build all projects from solution (except VB project on Unix platforms)
- Run unit tests (Windows - all targets, non-Windows - netcoreapp1.1)
- Run integration tests (Windows - all targets, non-Windows - netcoreapp1.1)
- Create nuget packages (only on Windows)

**Important!**. Exisiting custom build scripts from `build` directory are not affected, once new approach will  be used the custom scripts can be removed.

### CODE REVIEW

**Comment by AndreyAkinshin** [comment]
@Ky7m, thanks for the PR, it looks great! Right now I'm too busy on my work, so I will review it in a few days.

**Comment by Ky7m** [comment]
@AndreyAkinshin, no problems.

**Comment by AndreyAkinshin** [comment]
Hey @Ky7m, sorry for the huge delay, I finally found some time. =)

A few comments.
1. Could we make it possible to pack artifacts locally? Right now the `Pack` task has the following criteria: `AppVeyor.IsRunningOnAppVeyor && !AppVeyor.Environment.PullRequest.IsPullRequest`, however sometimes I want to build artifacts on my local machine. Right now I can run `build/build-and-pack.cmd`, but it would be more convinient to do it also in `build.cake`.
2. Could we introduce a `SkipTests` flag (for local use cases)?
3. I have some troubles on my local xubuntu machine:
```
Mono supports MSBuild. Override ToolPath value with `/usr/lib/mono/msbuild/15.0/bin/MSBuild.dll`
Microsoft (R) Build Engine version 15.2.0.0 ( Thu May 11 17:28:41 UTC 2017)
Copyright (C) Microsoft Corporation. All rights reserved.

  BenchmarkDotNet.Core -> /home/akinshin/sandbox/BenchmarkDotNet/src/BenchmarkDotNet.Core/bin/Release/net46/BenchmarkDotNet.Core.dll
  BenchmarkDotNet.Toolchains.Roslyn -> /home/akinshin/sandbox/BenchmarkDotNet/src/BenchmarkDotNet.Toolchains.Roslyn/bin/Release/net46/BenchmarkDotNet.Toolchains.Roslyn.dll
  BenchmarkDotNet -> /home/akinshin/sandbox/BenchmarkDotNet/src/BenchmarkDotNet/bin/Release/net46/BenchmarkDotNet.dll
  BenchmarkDotNet.Core -> /home/akinshin/sandbox/BenchmarkDotNet/src/BenchmarkDotNet.Core/bin/Release/netcoreapp1.1/BenchmarkDotNet.Core.dll
  BenchmarkDotNet -> /home/akinshin/sandbox/BenchmarkDotNet/src/BenchmarkDotNet/bin/Release/netcoreapp1.1/BenchmarkDotNet.dll
  BenchmarkDotNet.Diagnostics.Windows -> /home/akinshin/sandbox/BenchmarkDotNet/src/BenchmarkDotNet.Diagnostics.Windows/bin/Release/net46/BenchmarkDotNet.Diagnostics.Windows.dll
  BenchmarkDotNet.Samples -> /home/akinshin/sandbox/BenchmarkDotNet/samples/BenchmarkDotNet.Samples/bin/Release/netcoreapp1.1/BenchmarkDotNet.Samples.dll
  BenchmarkDotNet.Samples -> /home/akinshin/sandbox/BenchmarkDotNet/samples/BenchmarkDotNet.Samples/bin/Release/net46/win7-x86/BenchmarkDotNet.Samples.exe
  BenchmarkDotNet.Tests -> /home/akinshin/sandbox/BenchmarkDotNet/tests/BenchmarkDotNet.Tests/bin/Release/netcoreapp1.1/BenchmarkDotNet.Tests.dll
  BenchmarkDotNet.Tests -> /home/akinshin/sandbox/BenchmarkDotNet/tests/BenchmarkDotNet.Tests/bin/Release/net46/BenchmarkDotNet.Tests.dll
  BenchmarkDotNet.IntegrationTests.ConfigPerAssembly -> /home/akinshin/sandbox/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests.ConfigPerAssembly/bin/Release/netcoreapp1.1/BenchmarkDotNet.IntegrationTests.ConfigPerAssembly.dll
  BenchmarkDotNet.IntegrationTests.DisabledOptimizations -> /home/akinshin/sandbox/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests.DisabledOptimizations/bin/Release/netcoreapp1.1/BenchmarkDotNet.IntegrationTests.DisabledOptimizations.dll
  BenchmarkDotNet.IntegrationTests.EnabledOptimizations -> /home/akinshin/sandbox/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests.EnabledOptimizations/bin/Release/netcoreapp1.1/BenchmarkDotNet.IntegrationTests.EnabledOptimizations.dll
  BenchmarkDotNet.IntegrationTests -> /home/akinshin/sandbox/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/netcoreapp1.1/BenchmarkDotNet.IntegrationTests.dll
  BenchmarkDotNet.IntegrationTests.ConfigPerAssembly -> /home/akinshin/sandbox/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests.ConfigPerAssembly/bin/Release/net46/BenchmarkDotNet.IntegrationTests.ConfigPerAssembly.dll
  BenchmarkDotNet.IntegrationTests.DisabledOptimizations -> /home/akinshin/sandbox/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests.DisabledOptimizations/bin/Release/net46/BenchmarkDotNet.IntegrationTests.DisabledOptimizations.dll
  BenchmarkDotNet.IntegrationTests.EnabledOptimizations -> /home/akinshin/sandbox/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests.EnabledOptimizations/bin/Release/net46/BenchmarkDotNet.IntegrationTests.EnabledOptimizations.dll
  BenchmarkDotNet.IntegrationTests.CustomPaths -> /home/akinshin/sandbox/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests.CustomPaths/bin/Release/net46/BenchmarkDotNet.IntegrationTests.CustomPaths.dll
  BenchmarkDotNet.IntegrationTests -> /home/akinshin/sandbox/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests/bin/Release/net46/BenchmarkDotNet.IntegrationTests.dll
/home/akinshin/sandbox/BenchmarkDotNet/samples/BenchmarkDotNet.Samples.FSharp/BenchmarkDotNet.Samples.FSharp.fsproj(80,3): error MSB4102: The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.
/home/akinshin/sandbox/BenchmarkDotNet/tests/BenchmarkDotNet.IntegrationTests.FSharp/BenchmarkDotNet.IntegrationTests.FSharp.fsproj(55,3): error MSB4102: The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.
An error occurred when executing task 'Build'.

----------------------------------------
Teardown
----------------------------------------
Executing custom teardown action...
Deleting file /home/akinshin/sandbox/BenchmarkDotNet/BenchmarkDotNet.sln
Moving file BenchmarkDotNet.sln.build.backup to /home/akinshin/sandbox/BenchmarkDotNet/BenchmarkDotNet.sln
```
What should we do in such cases?

**Comment by Ky7m** [comment]
@AndreyAkinshin, I will do some changes to address 1st and 2d items and investigate a 3rd one.

**Comment by AndreyAkinshin** [comment]
@Ky7m, great, thanks!

**Comment by Ky7m** [comment]
@AndreyAkinshin, I added a few updates to this PR:

1.  Now, you can pack artifacts locally using **Pack** target
``
.\build.ps1 -Target Pack 
``
2. Introduced a new flag **SkipTests**
Windows
``
.\build.ps1 --SkipTests True
``
Linux/macOS
``
 ./build.sh --skiptests=true
``

Regarding your issue with F# project building, make sure that you have a **fsharp** package installed:

```
sudo apt-get update
sudo apt-get install fsharp
```

Let me know if it works for you.

**Comment by AndreyAkinshin** [comment]
@Ky7m, thanks again. On Linux everything works perfect. On Windows, `.\build.ps1 --SkipTests True` doesn't work:
```
λ  .\build.ps1 --SkipTests True
dotnet-install: .NET SDK version 1.0.4 is already installed.
dotnet-install: Adding to current process PATH: "W:\Work\BenchmarkDotNet\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
Running build script...
More than one build script specified.

Usage: Cake.exe [script] [--verbosity=value]
                [--showdescription] [--dryrun] [..]

Example: Cake.exe
Example: Cake.exe build.cake --verbosity=quiet
Example: Cake.exe build.cake --showdescription

Options:
    --verbosity=value    Specifies the amount of information to be displayed.
                         (Quiet, Minimal, Normal, Verbose, Diagnostic)
    --debug              Performs a debug.
    --showdescription    Shows description about tasks.
    --dryrun             Performs a dry run.
    --version            Displays version information.
    --help               Displays usage information.
    --mono               Uses the Mono Compiler, rather than Roslyn script engine.
    --experimental       Uses the nightly builds of Roslyn script engine.
```
But `.\build.ps1 --SkipTests=True` works pretty well. Are you sure about the equal sign?

And I have the final request before this PR will be merged: could you update BenchmarkDotNet\docs\guide\Contributing\ and write a few notes about Cake, build scripts, `-Target Pack`, and `--skiptests=true`?

**Comment by Ky7m** [comment]
@AndreyAkinshin, my apologies, I forgot to notify you about edited comment (first version was without '=' sign for Windows platform)

**Comment by Ky7m** [comment]
New commit brings updated 'Building' section in documentation. Preview https://github.com/Ky7m/BenchmarkDotNet/blob/489359e52a011f0d00844fc6321d589c2d5f4649/docs/guide/Contributing/Building.md

**Comment by AndreyAkinshin** [comment]
@Ky7m, it seems that now everything works fine on all operating systems and we have a nice guide about the building system. Thanks again for awesome PR!

**Comment by Ky7m** [comment]
@AndreyAkinshin, after merge I see that build is not successful due to some timeouts (re-run should help). And one thing is left, it is integration with TravisCI.

**Comment by AndreyAkinshin** [comment]
@Ky7m,
> after merge I see that build is not successful due to some timeouts (re-run should help). 
https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/history

re-runs don't help, we can't download nuget.exe. Any ideas?

> And one thing is left, it is integration with TravisCI.

Will do it, https://github.com/dotnet/BenchmarkDotNet/issues/496

**Comment by Ky7m** [comment]
@AndreyAkinshin, there is a temporary solution (override hosts file).
I have done it in my fork https://github.com/Ky7m/BenchmarkDotNet/blob/master/appveyor.yml#L30,L31
Do you want me to create a pull request?
Build with workaround https://ci.appveyor.com/project/IgorFesenko/benchmarkdotnet/build/0.10.8.54

**Comment by AndreyAkinshin** [comment]
@Ky7m,
> Do you want me to create a pull request?

Yes, it would be great.

**Comment by Ky7m** [comment]
@AndreyAkinshin, here you are #497 
Build run on PR - https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/build/0.10.8.250-oqlwmanw

**Comment by AndreyAkinshin** [comment]
@Ky7m, merged.

**Pull request merged**
