### PR TITLE
Fix CI build 

### LINKED ISSUE #588: Broken appveyor build
Lately, all of our builds on appveyor are red. Here is the error:

```
Locating binaries for framework netcoreapp2.0...
Running .NET Core 2.0 tests for framework netcoreapp2.0...
Cake.exe : The specified framework version '2.0' could not be parsed
At line:1 char:1
+ & "C:\projects\benchmarkdotnet\tools\Cake.0.23.0\Cake.exe" "build.cak ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The specified f...d not be parsed:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
The specified framework 'Microsoft.NETCore.App', version '2.0' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '2.0'.
An error occurred when executing task '
FastTests
'.
----------------------------------------
```
This problem can be reproduced locally (via `build.ps1`, Windows only).

Last successful build: https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/build/0.10.10.343
First failed build: https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/build/0.10.10.344

### PR DESCRIPTION
**Pull request by Ky7m**
Upgrade version to 2.0.3 and explicitly specify fx version to run tests against .netcoreapp2.0. Closes #588

### CODE REVIEW

**Comment by AndreyAkinshin** [comment]
@Ky7m, thanks!

**Comment by AndreyAkinshin** [comment]
Hooray, our build is green again: https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/build/0.10.10.350

**Comment by adamsitnik** [comment]
@Ky7m thanks for saving us again!

**Comment by Ky7m** [comment]
@adamsitnik, my pleasure!

**Pull request merged**
