### PR TITLE
EdPeltChangePointDetector improvements

### PR DESCRIPTION
**Pull request by jeanbern**
Turned the jagged array into a flat one.
Changed 2 lists into a pair of arrays and a single length counter. Got rid of Add, RemoveRange, and Clear calls by doing so.
I considered stackalloc Span<T>, but the arrays can get quite large and not fit the stack.

In GetSegmentCost I pulled `tau2 - tau1` out of the loop and also made indexing simpler.
In GetPartialSums I removed some array accesses by using a variable to store the previous value, and saved some writes by calculating the value before assigning it.

Added curly braces

Is there a reason it's not a static class?

### CODE REVIEW

**Comment by AndreyAkinshin** [comment]
@jeanbern thanks for the PR!
Do you have any benchmarks that show noticeable performance impact from your changes?

**Comment by jeanbern** [comment]
Running unit tests as benchmarks:

Before:

| Method |           Mean |         Error |        StdDev |
|------- |---------------:|--------------:|--------------:|
|  Test1 |       8.350 us |     0.1015 us |     0.0848 us |
|  Test2 |   3,554.749 us |    11.8809 us |    10.5321 us |
|  Test3 |       4.592 us |     0.0285 us |     0.0253 us |
|  Test4 |      16.173 us |     0.0864 us |     0.0808 us |
|  Test5 |   7,649.757 us |    39.3496 us |    32.8587 us |
|  Test6 | 492,407.260 us | 3,830.0268 us | 3,582.6095 us |


After:

| Method |           Mean |         Error |        StdDev |
|------- |---------------:|--------------:|--------------:|
|  Test1 |       6.354 us |     0.0446 us |     0.0372 us |
|  Test2 |   2,960.071 us |    22.6944 us |    20.1180 us |
|  Test3 |       3.463 us |     0.0089 us |     0.0074 us |
|  Test4 |      12.128 us |     0.0722 us |     0.0640 us |
|  Test5 |   4,802.458 us |    33.9739 us |    31.7792 us |
|  Test6 | 301,802.931 us | 1,945.7635 us | 1,624.8007 us |

**Comment by AndreyAkinshin** [comment]
@jeanbern sorry for the late review, I was extremely busy the last month =(

I pushed some fixed into your branch, here is an overview:
* Remove curly brackets from single-line statement to be consistent with the common code style in BenchmarkDotNet
* Improve readability: add some comments here and there, rename some variables, etc.
* Rollback the `do/while` loop in `GetPartialSums` back to a simple for. According to my measurements, the `do/while` doesn't provide a noticeable performance improvement, but it significantly reduces the code readability

Let me know what do you think. If you are OK with the changes, I'm ready to merge the branch.

In general, the PR is great! Replacing two-dimensional array by a single-dimensional one produced a very good overall performance impact!

> Is there a reason it's not a static class?

Yes, I'm going to implement a few additional algorithms for changepoint detection and define a common interface for them.

**Comment by jeanbern** [comment]
@AndreyAkinshin Looks good to me, thank you for taking the time to go over it and explain your changes. I'll keep the comments in mind when I submit PR in the future.

**Pull request merged**
