### PR TITLE
use coalesce instead of join

### PR DESCRIPTION
**Pull request by askazakov**
simplify template.json

### CODE REVIEW

**Comment by timcassell** [comment]
Templates were updated in #2338. Is this still relevant? Also, what does coalesce do? I'm not familiar with the templates. @askazakov cc @YegorStepanov

**Comment by askazakov** [comment]
> Templates were updated in #2338. Is this still relevant? Also, what does coalesce do? I'm not familiar with the templates. @askazakov cc @YegorStepanov

Yes, it is still relevant. It's nothing but refactoring. Try to do a little bit more clean code.

Docs for `coalesce` is here https://github.com/dotnet/templating/wiki/Available-Symbols-Generators#coalesce (in short `coalesce` behaves like the C# `??` operator)

pr logic is something like 

- `framework` either set via parameters or empty by default
- `frameworkDefault` depends only on app type (console or not)
- `frameworkValue` = framework ?? frameworkDefault (if `framework` is set then use it's value, if not use `frameworkDefault` accordingly app type

**Comment by askazakov** [comment]
@timcassell @YegorStepanov any updates?

**Comment by timcassell** [comment]
Yegor is currently busy, he should be available to review this soon.

**Comment by askazakov** [comment]
@timcassell @YegorStepanov any updates?

**Comment by timcassell** [comment]
@AndreyAkinshin Perhaps you could give this a look if @YegorStepanov isn't around?

**Review by AndreyAkinshin — APPROVED** [review]

**Comment by AndreyAkinshin** [comment]
@askazakov thanks for the PR and sorry for such a late merge.

**Pull request merged**
