### PR TITLE
Change mono-config.js format in the Wasm Tool Chain for ICU support

### PR DESCRIPTION
**Pull request by naricc**
This change uses an updated format for the mono-config.js generated in the wasm tool chain. This allows wasm to be used with ICU support for globalization (it otherwise would run in invariant globalization mode).

Fixes: https://github.com/dotnet/BenchmarkDotNet/issues/1504

### CODE REVIEW

**Comment by naricc** [comment]
@adamsitnik

**Comment by akoeplinger** [comment]
@AndreyAkinshin do you think we could merge this PR?

**Comment by AndreyAkinshin** [comment]
@akoeplinger looks good to me.
@adamsitnik could you please also take a look?

**Comment by DrewScoggins** [comment]
@adamsitnik is on vacation until August 3rd.

**Pull request merged**
