### PR TITLE
Logical group support, fixes #617

### LINKED ISSUE #617: Allow baseline per category
Edit: if there's already a way to do this and I'm just being ignorant: please say!

Often I'm trying to compare alternative implementations that can impact multiple scenarios - essentially baseline vs option 1 (vs option 2 etc), but for multiple *separate* tests A, B, C.

The `Baseline = true`  feature is great, but only really allows a single baseline. If multiple methods are marked as `Baseline`, then the test runner fails and complains at you.

However, `[BenchmarkCategory(...)]` exists (via #248). It is currently only used to *filter* tests to run, but it could be much richer:

- the result grids could be split by category
- the relative comparisons against baseline could be *computed* by category

so instead of:

```
                   Method |         Mean |      Error |     StdDev |      Op/s | Scaled | ScaledSD |    Gen 0 |   Gen 1 |  Allocated |
------------------------- |-------------:|-----------:|-----------:|----------:|-------:|---------:|---------:|--------:|-----------:|
         'single, Stream' |     61.32 us |  1.2102 us |  1.8842 us | 16,309.04 |   1.00 |     0.00 |   2.2583 |  0.0292 |   13.88 KB |
 'single, ReadOnlyBuffer' |     52.98 us |  0.1676 us |  0.1568 us | 18,874.14 |   0.86 |     0.03 |   2.2583 |  0.0042 |   13.88 KB |
          'multi, Stream' | 14,285.07 us | 54.3681 us | 50.8560 us |     70.00 | 233.18 |     6.95 | 564.1667 | 10.0000 | 3470.77 KB |
  'multi, ReadOnlyBuffer' | 13,219.59 us | 34.1087 us | 31.9053 us |     75.65 | 215.79 |     6.41 | 564.1667 |  0.8333 | 3470.76 KB |
```

we could have:

```

Category: 'multi'

                   Method |         Mean |      Error |     StdDev |      Op/s | Scaled | ScaledSD |    Gen 0 |   Gen 1 |  Allocated |
------------------------- |-------------:|-----------:|-----------:|----------:|-------:|---------:|---------:|--------:|-----------:|
                 'Stream' |     61.32 us |  1.2102 us |  1.8842 us | 16,309.04 |   1.00 |     0.00 |   2.2583 |  0.0292 |   13.88 KB |
         'ReadOnlyBuffer' |     52.98 us |  0.1676 us |  0.1568 us | 18,874.14 |   0.86 |     0.03 |   2.2583 |  0.0042 |   13.88 KB |

Category: 'single'

                   Method |         Mean |      Error |     StdDev |      Op/s | Scaled | ScaledSD |    Gen 0 |   Gen 1 |  Allocated |
------------------------- |-------------:|-----------:|-----------:|----------:|-------:|---------:|---------:|--------:|-----------:|
                 'Stream' | 14,285.07 us | 54.3681 us | 50.8560 us |     70.00 |   1.00 |     *.** | 564.1667 | 10.0000 | 3470.77 KB |
         'ReadOnlyBuffer' | 13,219.59 us | 34.1087 us | 31.9053 us |     75.65 |   0.93 |     *.** | 564.1667 |  0.8333 | 3470.76 KB |
```

with `Scaled` / `ScaledSD` being relative to the `Baseline` (if one) in that same category.

(*.** is just where I haven't "done the math" by hand; to be clear: "single" and "multi" here are completely different tests - it isn't just more of the same - naming is hard)

If necessary, this could be an opt-in `SplitResultsByCategory` feature on custom options. Or it could be implicit: "there's multiple baselines == split by category" (since this won't have worked previously, this can't change existing *working* behaviour)

### PR DESCRIPTION
**Pull request by AndreyAkinshin**

### CODE REVIEW

**Comment by AndreyAkinshin** [comment]
@mgravell, @adamsitnik, ok, the feature is implemented, any comments are welcome.
You can find basic usage examples in `docs/guide/Advanced/Baseline.md`.
`tests/BenchmarkDotNet.Tests/Exporters/MarkdownExporterApprovalTests.cs` contains a lot of additional examples and corner cases. You can find expected outputs for all these cases in the `tests/BenchmarkDotNet.Tests/Exporters/ApprovedFiles` folder.

**Comment by mgravell** [comment]
@AndreyAkinshin holy goat, that's an impressive turnaround time; I'll give it a whirl as soon as I can; is there a location for pre-built? (it doesn't seem updated on nuget)

**Comment by AndreyAkinshin** [comment]
@mgravell, the NuGet package (you need BenchmarkDotNet 0.10.11.386) will be published to our [nightly feed](http://benchmarkdotnet.org/Guides/NuGet.htm#nightly) (`https://ci.appveyor.com/nuget/benchmarkdotnet`) as soon as [this build](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/build/0.10.11.386-fcxekiwr) finishes (in the case if all the integration tests are green).

**Comment by AndreyAkinshin** [comment]
@mgravell, hooray, the tests are green! BenchmarkDotNet 0.10.11.385 is ready (in the nightly feed), you can already use it.

**Comment by mgravell** [comment]
@AndreyAkinshin verified with my test suite - looks great! Awesome job, much appreciated.

```
                 Method |  Categories |         Mean |       Error |      StdDev |      Op/s | Scaled | ScaledSD |     Gen 0 |    Gen 1 |    Gen 2 |   Allocated |
----------------------- |------------ |-------------:|------------:|------------:|----------:|-------:|---------:|----------:|---------:|---------:|------------:|
                 Stream |  multi read | 14,161.96 us | 169.5618 us | 141.5918 us |     70.61 |   1.00 |     0.00 | 2812.5000 |  62.5000 |        - | 17353.86 KB |
         ReadOnlyBuffer |  multi read | 13,541.34 us |  28.3219 us |  22.1119 us |     73.85 |   0.96 |     0.01 | 2812.5000 |  62.5000 |        - | 17353.79 KB |
                        |             |              |             |             |           |        |          |           |          |          |             |
   'Pipe, single alloc' | multi write |     64.37 us |   0.3536 us |   0.2953 us | 15,536.28 |   1.51 |     0.06 |         - |        - |        - |      8.8 KB |
 'Pipe, alloc per item' | multi write |     64.69 us |   0.1112 us |   0.0985 us | 15,458.91 |   1.52 |     0.06 |         - |        - |        - |      8.8 KB |
                 Stream | multi write |     42.67 us |   0.8672 us |   1.8292 us | 23,437.11 |   1.00 |     0.00 |  378.9063 | 246.0938 | 246.0938 |  1678.18 KB |
                        |             |              |             |             |           |        |          |           |          |          |             |
 'Pipe, alloc per item' |  read/write |    127.84 us |   0.5419 us |   0.4525 us |  7,822.48 |   1.12 |     0.09 |  109.3750 |        - |        - |   703.05 KB |
                 Stream |  read/write |    115.33 us |   3.3934 us |  10.0054 us |  8,670.80 |   1.00 |     0.00 |  484.3750 | 250.0000 | 242.1875 |  2372.61 KB |
                        |             |              |             |             |           |        |          |           |          |          |             |
                 Stream | single read |     60.20 us |   0.5085 us |   0.3970 us | 16,612.47 |   1.00 |     0.00 |  562.5000 |  15.6250 |        - |  3470.77 KB |
         ReadOnlyBuffer | single read |     54.68 us |   0.1925 us |   0.1607 us | 18,287.85 |   0.91 |     0.01 |  562.5000 |  15.6250 |        - |   3470.7 KB |
```

**Comment by AndreyAkinshin** [comment]
@mgravell, great!
@adamsitnik, could you review these changes?

**Pull request merged**
