### PR TITLE
Fix wasm toolchain

### PR DESCRIPTION
**Pull request by timcassell**
I think this should fix https://github.com/dotnet/performance/issues/3984, but I couldn't get wasm to work locally, so I couldn't test it. PTAL @LoopedBard3

### CODE REVIEW

**Comment by LoopedBard3** [comment]
I think this is along the correct path for the fix, but this specific iteration ends up hitting this error when trying to generate the boiler plate code:
```
// Generate Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/pbibus/performance/artifacts/bin/MicroBenchmarks/Release/net9.0/Job-SXNDZX/bin/Release/net9.0/browser-wasm/AppBundle/test-main.js.config'.
    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
    at System.IO.File.Create(String path)
    at BenchmarkDotNet.Toolchains.GeneratorBase.GenerateAppConfig(BuildPartition buildPartition, ArtifactsPaths artifactsPaths)
    at BenchmarkDotNet.Toolchains.GeneratorBase.GenerateProject(BuildPartition buildPartition, ILogger logger, String rootArtifactsFolderPath)
// BenchmarkDotNet has failed to build the auto-generated boilerplate code
```

**Comment by LoopedBard3** [comment]
I am still trying out some things. I will keep the main tracking issue updated with any findings and what not 👍.

**Comment by caaavik-msft** [comment]
I believe adding `artifactsPaths.AppConfigPath.EnsureFolderExists();` to `GeneratorBase.GenerateAppConfig()` will fix this issue.

**Comment by caaavik-msft** [comment]
I've made a PR to add an integration test which should help with local testing, you need to have the wasm-tools workload installed (`dotnet workload install wasm-tools`) and have installed the `v8` engine though: https://github.com/dotnet/BenchmarkDotNet/pull/2532

**Comment by timcassell** [comment]
> and have installed the `v8` engine

Yeah, that's the part I got stuck on on my Windows machine. 😞

**Comment by timcassell** [comment]
> I believe adding `artifactsPaths.AppConfigPath.EnsureFolderExists();` to `GeneratorBase.GenerateAppConfig()` will fix this issue. The problem is that the `AppBundle` folder doesn't exist yet when it tries to generate the app config.

@LoopedBard3 Does that change make it work?

**Comment by LoopedBard3** [comment]
I did get a successful local run with the branch for the PR caaavik put up: https://github.com/dotnet/BenchmarkDotNet/pull/2532

**Review by caaavik-msft — APPROVED** [review]

**Comment by LoopedBard3** [comment]
This ran successfully with a local wasm wasm test run. 👍

**Review by LoopedBard3 — APPROVED** [review]

**Review by adamsitnik — APPROVED** [review]
@timcassell thanks a lot! LGTM!

**Pull request merged**
