### PR TITLE
Increase max supported affinity from 31 to 64 (#2211)

### PR DESCRIPTION
**Pull request by Donis-**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/BenchmarkDotNet?pullRequest=2228) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/BenchmarkDotNet?pullRequest=2228) before we can accept your contribution.<br/><br/>:x: Donis- [sign now](https://cla.dotnetfoundation.org/dotnet/BenchmarkDotNet?pullRequest=2228)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/BenchmarkDotNet?pullRequest=2228) it.</sub>

**Comment by Donis-** [comment]
CLA sign now seems broken, any other way to approve?

**Comment by Donis-** [comment]
@adamsitnik is it possible to merge this?

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @Donis- !

**Pull request merged**
