### PR TITLE
Log shows a wrong name for plot images #1181

### PR DESCRIPTION
**Pull request by marcnet80**
https://github.com/dotnet/BenchmarkDotNet/issues/1181

### CODE REVIEW

**Comment by AndreyAkinshin** [comment]
@marcnet80 I think it will be better to fix it on the level of `RPlotExporter`. By convention, `ExportToFiles` returns the list of generated files. Currently, it still returns the boxplot/barplot pair with incorrect names.

**Comment by marcnet80** [comment]
@AndreyAkinshin, I want to clarify, do you mean that instead of incorrect filename need show "*" asterix in log for RPlotExporter images only? 
Result will be:
```
*-boxplot.png
*-barplot.png
```

**Comment by AndreyAkinshin** [comment]
@marcnet80 I suggest displaying just a single item `*.png`.

**Comment by marcnet80** [comment]
@AndreyAkinshin, please reivew the last changes. Thank you.

**Comment by AndreyAkinshin** [comment]
@marcnet80 thanks!

**Pull request merged**
