### PR TITLE
make allocation quantum public, deal with a spelling error and expose…

### PR DESCRIPTION
**Pull request by RichLinnell**
… allocation quantum on benchmark environment info re issue #450

### CODE REVIEW

**Comment by AndreyAkinshin** [comment]
@RichLinnell, thanks!

**Comment by RichLinnell** [comment]
@AndreyAkinshin I have completed it.

**Comment by AndreyAkinshin** [comment]
@richlander, could you try to do it again? The .NET Foundation Pull Request bot should mark the PR with the `cla-signed` label (an example: https://github.com/dotnet/BenchmarkDotNet/pull/451)

**Comment by AndreyAkinshin** [comment]
@richlander, now everything is ok. Thanks again for the PR.

**Pull request merged**
