### PR TITLE
[WIP] Add annotations for diassembler output #545 draft

### PR DESCRIPTION
**Pull request by GeorgePlotnikov**
Please review current draft of #545. _Idea description_ I've created the similar to CLR JitDisasm output:
```
; ============================================================
; Assembly listing for method DomainBoundILStubClass:IL_STUB_PInvoke(long):int
; Emitting BLENDED_CODE for X64 CPU with AVX
; optimized code
; rbp based frame
; partially interruptible
; Final local variable assignments
; Total bytes of code 172, prolog size 28 for method DomainBoundILStubClass:IL_STUB_PInvoke(long):int
```
class

```
public class DisassembledMethodAnnotation
{
    public int TotalBytesOfCode { get; set; }
    public bool IsOptmizedCode { get; set; }
    public bool IsFullyinterruptible { get; set; }
}
```
which fills arount [this](https://github.com/GeorgePlotnikov/BenchmarkDotNet/blob/add-annotations-for-diassembler-output/src/BenchmarkDotNet.Disassembler.x64/Program.cs#L215) line.

Currently, as a result we can have something like:
```
============Disassembly annotation================
total bytes of code 74 
optimized code 
partially interruptible 
AXV supported
============================================ 
00007ff9`733f5280 System.Collections.Generic.List`1[[System.Int32, mscorlib]].Add(Int32)
--
```
Please provide your feedback.

### CODE REVIEW

**Comment by AndreyAkinshin** [comment]
@adamsitnik, could you please review this PR?

**Comment by adamsitnik** [comment]
hi @GeorgePlotnikov 

Please excuse me for a very late reply.

The code looks good. I can see that you have managed to get all information for the header file summary.

However, I have never used the output created by CoreCLR.  I think that it would be good to ask Joseph what are the most important information that he would like to see in BDN's diasm. After this, your research should tell if we can get this info or not or what part of it.  I am going to post a reply in the initial issue and tag you.

**Comment by GeorgePlotnikov** [comment]
hi @adamsitnik, thanks a lot!

**Comment by GeorgePlotnikov** [comment]
Something went wrong with the git, looks like it tried to merge with current master branch and made a mess. @adamsitnik, @AndreyAkinshin guys, do u have any idea how to solve it, keeping my changes. Thanks in advance!

**Comment by AndreyAkinshin** [comment]
@GeorgePlotnikov, I think that the best option for you is squashing commits locally into one commit and rebasing this commit on the `origin/master` (you can do force push in your branch).

**Comment by GeorgePlotnikov** [comment]
@AndreyAkinshin thanks for hinting direction how to fix it, appreciate you. Will add couple more features to output.

**Comment by AndreyAkinshin** [comment]
@GeorgePlotnikov what the current status of this PR?

**Comment by adamsitnik** [comment]
@AndreyAkinshin I had a chat with @GeorgePlotnikov about it, we are going to close it because of the fact that the person who could validate this feature no longer works for JIT Team

**Pull request closed without merging**
