### PR TITLE
Add Support for Warning Logging and Integrate with Visual Studio Test Logging

### PR DESCRIPTION
**Pull request by sheffer21**
This pull request adds support for warning logging and integrates this new functionality with the Visual Studio test logging framework.

### CODE REVIEW

**Comment by sheffer21** [comment]
@dotnet-policy-service agree

**Comment by adamsitnik** [comment]
@caaavik-msft PTAL

**Review by caaavik-msft — APPROVED** [review]
LGTM

**Comment by sheffer21** [comment]
@adamsitnik could you please review this PR? Thanks!

**Pull request merged**
