### PR TITLE
Add single quote when use pattern with filters

### PR DESCRIPTION
**Pull request by erlangxk**

### CODE REVIEW

**Review by AndreyAkinshin — CHANGES_REQUESTED** [review]
@erlangxk, you have used the wrong type of quotes (`‘’` instead of `''`)

**Comment by erlangxk** [comment]
very weried, I don't know what is that single quote I used in the first commit. maybe I use some non-English input method that time.

**Review by AndreyAkinshin — APPROVED** [review]

**Comment by AndreyAkinshin** [comment]
@erlangxk thanks!

**Comment by AndreyAkinshin** [comment]
@erlangxk I just realized that this PR was to the `docs-stable` branch. According to the current workflow, all the documentation changes should be merged to the `master` branch and cherry-picked to the `docs-stable`. Once another release version is published, `docs-stable` is moving to the latest `master`. This allows us to maintain a nicer git history and track changes in a more transparent way. Sorry, but I lost your commit in `v0.13.3`. Just cherry-picked it to `master`, it will be included in `v0.13.4`.

**Pull request merged**
