### PR TITLE
Fix build after styleCop

### PR DESCRIPTION
**Pull request by WojciechNagorski**
Use StyleCop and FxCop only from `BenchmarkDotNet.sln`.

### CODE REVIEW

**Comment by adamsitnik** [comment]
@WojciechNagorski  is it going to solve the missing ruleset file problem?

**Comment by WojciechNagorski** [comment]
@adamsitnik Sometimes builds on AppVeyor don't work 
image

StyleCop and FxCop should not use in autogenerated project.

**Comment by WojciechNagorski** [comment]
Because of tests are run with `--no-build`
https://github.com/dotnet/BenchmarkDotNet/blob/294320be9525b0ecfefd0351381756d3a3b77211/build.cake#L230
StyleCop is used in automatically generated projects. It causes that the build works longer than 60 min. AppVeyor has a limit and returns the message: `Build execution time has reached the maximum allowed time for your plan (60 minutes).` example: https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/builds/31261936/messages

I need more time to find a workaround for this.

**Comment by adamsitnik** [comment]
@WojciechNagorski perhaps we should somehow disable any kind of static analysis tools in the auto-generated projects? This is what we have as of today:

https://github.com/dotnet/BenchmarkDotNet/blob/294320be9525b0ecfefd0351381756d3a3b77211/src/BenchmarkDotNet/Templates/CsProj.txt#L17

Another idea that comes to my mind is to check how the csproj setting that disables static code analysis translates to an msbuild property and add it to the list of arguments when we are running `dotnet build` and `dotnet publish`:

https://github.com/dotnet/BenchmarkDotNet/blob/294320be9525b0ecfefd0351381756d3a3b77211/src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs#L155

**Comment by WojciechNagorski** [comment]
@adamsitnik I've done it 😄 
https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/builds/31287737

### Description

The reason is really complicated. I can describe it with the following example:

Firstly, the entire solution is built using `BenchmarkDotNet.sln` so `$(SolutionDir)` works correctly and `<CodeAnalysisRuleSet>` has correct value.

Before StyleCop the `ValidCommandLineArgumentsAreProperlyHandled` test had taken 934 ms. After StyleCop it took 11 sec 668 ms.
So I narrowed my search to this one test. It is run from cake with parameters:
```
dotnet test ./tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj -c Release -f netcoreapp2.1 --no-build --no-restore --filter ValidCommandLineArgumentsAreProperlyHandled -v n --logger trx
```
I added some additional logs to output and I got:

```
[...]
// start dotnet build -c Release  --no-restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 in C:\work\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests\bin\Release\netcoreapp2.1\Dry
// command took 54.65s and exited with 1
// BUILD RESULT Time Elapsed 00:00:53.70
    18 Error(s)
    138 Warning(s)
C:\Program Files\dotnet\sdk\3.1.101\Microsoft.Common.CurrentVersion.targets(4384,5): error MSB3021: Unable to copy file "C:\work\BenchmarkDotNet\tests\BenchmarkDotNet.Tests\bin\Release\netcoreapp2.1\BenchmarkDotNet.Tests.dll" to "bin\Release\netcoreapp2.1\BenchmarkDotNet.Tests.dll". The process cannot access the file 'C:\work\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests\bin\Release\netcoreapp2.1\BenchmarkDotNet.Tests.dll' because it is being used by another process. [C:\work\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests\BenchmarkDotNet.IntegrationTests.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Microsoft.Common.CurrentVersion.targets(4384,5): error MSB3027: Could not copy "C:\work\BenchmarkDotNet\tests\BenchmarkDotNet.Tests\bin\Release\netcoreapp2.1\BenchmarkDotNet.Tests.dll" to "bin\Release\netcoreapp2.1\BenchmarkDotNet.Tests.dll". Exceeded retry count of 10. Failed.  [C:\work\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests\BenchmarkDotNet.IntegrationTests.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Microsoft.Common.CurrentVersion.targets(4384,5): error MSB3021: Unable to copy file "C:\work\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests.VisualBasic\bin\Release\netcoreapp2.1\BenchmarkDotNet.IntegrationTests.VisualBasic.dll" to "bin\Release\netcoreapp2.1\BenchmarkDotNet.IntegrationTests.VisualBasic.dll". The process cannot access the file 'C:\work\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests\bin\Release\netcoreapp2.1\BenchmarkDotNet.IntegrationTests.VisualBasic.dll' because it is being used by another process. [C:\work\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests\BenchmarkDotNet.IntegrationTests.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Microsoft.Common.CurrentVersion.targets(4384,5): error MSB3027: Could not copy "C:\work\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests.VisualBasic\bin\Release\netcoreapp2.1\BenchmarkDotNet.IntegrationTests.VisualBasic.dll" to "bin\Release\netcoreapp2.1\BenchmarkDotNet.IntegrationTests.VisualBasic.dll". Exceeded retry count of 10. Failed.  [C:\work\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests\BenchmarkDotNet.IntegrationTests.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Microsoft.Common.CurrentVersion.targets(4384,5): error MSB3021: Unable to copy file "C:\work\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests.Static\bin\Release\netcoreapp2.1\BenchmarkDotNet.IntegrationTests.Static.dll" to "bin\Release\netcoreapp2.1\BenchmarkDotNet.IntegrationTests.Static.dll". The process cannot access the file 'C:\work\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests\bin\Release\netcoreapp2.1\BenchmarkDotNet.IntegrationTests.Static.dll' because it is being used by another process. [C:\work\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests\BenchmarkDotNet.IntegrationTests.csproj]
[...]
```

The most interesting is `The process cannot access the file [...]BenchmarkDotNet.[...].dll' because it is being used by another process` and `Exceeded retry count of 10` on every dll. 
The autogenerated project has a reference to `csproj` not to `dll`:
```
  <ItemGroup>
    <ProjectReference Include="C:\work\BenchmarkDotNet\tests\BenchmarkDotNet.IntegrationTests\BenchmarkDotNet.IntegrationTests.csproj" />
  </ItemGroup>
```
The build of autogenerated project is executed from `BenchmarkDotNet.IntegrationTests.dll` with the `--no-build` flag. Because the build of the autogenerated project is not run from `BenchmarkDotNet.sln` the `$(SolutionDir)` parameter doesn't have correct value. Because of the `<CodeAnalysisRuleSet>` value from `common.props` is different, the `BenchmarkDotNet.IntegrationTests.csproj` project require rebuild. But this project and all referenced projects are executed so it is imposible rebuild them. It causes `Exceeded retry count of 10. ` and it takes a lot of time.

### Solution

I've changed `$(SolutionDir)` to `$(MSBuildThisFileDirectory)`. I've found this solution in the `corefx` repo:
https://github.com/dotnet/corefx/blob/8a3ffed558ddf943c1efa87d693227722d6af094/src/Directory.Build.props#L13
And `CodeAnalysisRuleSet` have always the same value and `BenchmarkDotNet.IntegrationTests.csproj` doesn't require rebuild during building of the autogenerated project.

**Pull request merged**
