### PR TITLE
EnvironmentAnalyser - Warning about installed AV software 

### PR DESCRIPTION
**Pull request by lukasz-pyrzyk**
According  to the #364

EnvironmentAnalyzer prints warning about any antivirus software and tip for user about InProcessToolchain

### CODE REVIEW

**Comment by adamsitnik** [comment]
@lukasz-pyrzyk thanks!

@AndreyAkinshin LGTM. Please merge if you agree.

**Comment by AndreyAkinshin** [comment]
1. This PR includes two commits (AV+typo fixes). Please, create a separate feature branch for the PR in your fork based on the current master branch in `dotnet/BenchmarkDotNet`. The feature branch should include only this single commit.
2. The code with ManagementObjectSearcher makes sense only on Windows. Please, add the corresponded check.
3. I'm not sure that we *always* should print *a warning* about antiviruses. A lot of people have enabled WindowsDefender, but it doesn't affect benchmarks in most cases. If BenchmarkDotNet will always print a warning about it, probably it is not a good warning. It would be better to detect "suspicious" situation and warn user only in case of problems. @adamsitnik, what do you think?
4. It also makes sense to print path to the antivirus product exe. For example, if I run
```
wmic /NAMESPACE:\\root\SecurityCenter2 PATH AntiVirusProduct GET 
```
I get the following on my Windows machine:
```
displayName       instanceGuid                            pathToSignedProductExe                       pathToSignedReportingExe                     productState  timestamp
Windows Defender  {D68DDC3A-831F-4fae-9E44-DA132C1ACF46}  %ProgramFiles%\Windows Defender\MSASCui.exe  %ProgramFiles%\Windows Defender\MsMpeng.exe  397568        Fri, 28 Jul 2017 13:17:20 GMT
```
`pathToSignedProductExe` looks like a good option.

**Comment by lukasz-pyrzyk** [comment]
Hi @AndreyAkinshin, @adamsitnik, thanks for comments.
a) Sure, my fault
b) Totally agree, will do
c) I can walk through Summary and check if any benchmark exited with error code != 0. If yes, print a warning. What do you think about it? 
d) Will add

**Comment by AndreyAkinshin** [comment]
a,b,d) Ok, great.
c) LGTM. @adamsitnik?

**Comment by adamsitnik** [comment]
>  I can walk through Summary and check if any benchmark exited with error code != 0. If yes, print a warning. What do you think about it?

good idea!

**Pull request closed without merging**
