### PR TITLE
Fix consume ValueTask backed by IValueTaskSource

### LINKED ISSUE #1595: ValueTask-returning benchmarks are not being called correctly
When a benchmark returns a `ValueTask`, it is simply called with `.GetAwaiter().GetResult()`.

This is illegal `ValueTask` usage: you must not call `GetResult()` until the task has been completed.

`IValueTaskSource`-backed tasks do not need to support blocking on `GetResult()`. The in-box `ManualResetValueTaskSourceCore` does not support blocking `GetResult()`. Nor does the `DOTNET_SYSTEM_THREADING_POOLASYNCVALUETASKS` feature in .NET 5.

Instead, the `ValueTask` should be converted to a `Task` first:

```c#
static void BlockForResult(ValueTask task)
{
    if (task.IsCompleted)
        task.GetAwaiter().GetResult();
    else
        task.AsTask().GetAwaiter().GetResult();
}
```

(This will be unfortunate for the memory diagnoser, as a bogus `Task` will show up, but the alternative is to just crash...)

### PR DESCRIPTION
**Pull request by timcassell**
Fixes #1595.

This was originally #1941, but I split it out to just include the `ValueTask` fixes (and I added more tests).

### CODE REVIEW

**Comment by timcassell** [comment]
I'm pretty sure the test failures are unrelated. Other PRs are failing on the same tests.

**Comment by timcassell** [comment]
@adamsitnik Can you take a look?

**Comment by timcassell** [comment]
@AndreyAkinshin `InProcessToolchain` has been deprecated in favor of `InProcessNoEmitToolchain` since #1123 (almost 4 years ago). I updated it to match the changes I made here and in my other followup PRs, but I wonder if it can just be removed? Or should I just not add the updates and leave it in its old state? It's not good to maintain both.

**Comment by AndreyAkinshin** [comment]
I have no objection to removing `InProcessToolchain`. @adamsitnik what do you think?

**Comment by timcassell** [comment]
@ig-sinicyn I touched the InProcess toolchains here, can you take a look?

**Review by ig-sinicyn — APPROVED** [review]

**Comment by ig-sinicyn** [comment]
@timcassell, great job!

There should be a diff test that proves that emitted IL matches with compiled c# code. If it passes, all should be fine.

**Review by AndreyAkinshin — APPROVED** [review]
No concerns from my side. If @adamsitnik has no objections, we can merge it.

**Pull request merged**
