### PR TITLE
Use Pipes for host and benchmark process communication

### LINKED ISSUE #2070: BenchmarkDotNet crashing on Linux with DisassemblyDiagnoser
Opening as per https://github.com/dotnet/BenchmarkDotNet/issues/2000#issuecomment-1203883513.

My configuration is:
Kubuntu 20.04
and the provided commands return:
```
xterm-256color


pl_PL.UTF-8
```
(the middle ones don't return anything)

### PR DESCRIPTION
**Pull request by adamsitnik**
I definitely need to do more testing (Unix, Mono, WASM), but to tell the long story short redirecting STDIN & OUT and using it for process communication has historically proven to be unreliable. We can just use Anonymous Pipes and avoid issues like #2070.

Moreover, by using Pipes we could allow for:
- quiet mode: https://github.com/dotnet/BenchmarkDotNet/issues/190 (the processes can talk, but just don't print stuff to output)
- serializing custom types and doing things like https://github.com/dotnet/BenchmarkDotNet/issues/784 (this would require exposing new API, but that is fine)

Until I am done with everything this PR is a draft

fixes #2070

### CODE REVIEW

**Comment by adamsitnik** [comment]
The tests are failing because they are relying on writing some custom messages to standard ouput. Since it's not redirected anymore and we don't parse it, they are failing. I'll just rewrite them to write to specific file instead.

**Comment by adamsitnik** [comment]
@EgorBo and @stephentoub reported offline an issue where having the std out redirected and BDN reading from it can cause hangs when `DOTNET_JitDisasmSummary` is enabled.

Repro:

```cs
[2:19 PM] Egor Bogatov
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System;
[DisassemblyDiagnoser]
[HideColumns("Error", "StdDev", "Median", "RatioSD")]
public partial class Program
{
    static void Main(string[] args) => BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);
    private static readonly int s_year = DateTime.UtcNow.Year;
    [Benchmark]
    public int Count()
    {
        int count = 0;
        for (int i = 0; i < 1_000_000; i++)
        {
            if (s_year == 2021)
            {
                count++;
            }
        }
        return count;
    }
}
```

```cmd
$env:DOTNET_JitDisasmSummary=1
dotnet run -c Release -f net7.0 --filter *
```

Once I get back to working on this PR I am going to ensure that this scenario works as expected.

**Comment by adamsitnik** [comment]
I was able to confirm that this PR solves the problem reported by @stephentoub and @EgorBo

Previously it was hanging:

image

Now it works fine:

image

**Comment by adamsitnik** [comment]
I've tested locally .NET Framework, .NET (Core), Mono (the old one) and WASM (this was not easy due to missing docs). Everything works fine, merging.

**Comment by YegorStepanov** [comment]
The  deadlock on an unhandled exception occurs [here](https://github.com/dotnet/BenchmarkDotNet/pull/2092/files#diff-2a7da1208e90b7fc444cb8e20e424674d94b66aaac41ab6c5b35449f0b79d4fbR43):
```C#
[Benchmark]
public unsafe void Benchmark_UnhandledException()
{
    *(byte*)65536 = 100;
}
```
---

Slightly relevant here:

To proper detect the unhandled exception (#1661) and display its message we should set `process.RedirectStandardError=true` and read from **StandardError**, but it will another deadlock (#1631)

**Pull request merged**
