### PR TITLE
fix: filename issue

### PR DESCRIPTION
**Pull request by lonyehan**

### CODE REVIEW

**Comment by lonyehan** [comment]
@dotnet-policy-service agree

**Comment by lonyehan** [comment]
@dotnet-policy-service agree

**Comment by AndreyAkinshin** [comment]
@lonyehan what is the filename problem exactly?

**Comment by lonyehan** [comment]
> @lonyehan what is the filename problem exactly?
I changed the file name from “src\BenchmarkDotNet\Jobs\JobMode`1.cs” to “src\BenchmarkDotNet\Jobs\JobMode.cs”

**Comment by AndreyAkinshin** [comment]
@lonyehan What issue do you experience with the current file name?

**Comment by lonyehan** [comment]
I review it again, it's my misunderstand.

**Pull request closed without merging**
