### PR TITLE
Add EnumParam preserving type information

### LINKED ISSUE #1262: Params attribute doesn`t work in F# if you specify more than one enum value in constructor
Benchmark fails with error:   
Cannot implicitly convert type 'int' to 'Test.TestParam'. An explicit conversion exists (are you missing a cast?)

Here is code:

```
type TestParam = | A = 0 | B = 1

type IntroParams() =
    [<Params(TestParam.A, TestParam.B)>]
    member val A = TestParam.A with get, set

    [<Benchmark>]
    member this.Benchmark() =  Thread.Sleep((int)(this.A));
```

If you specify only  `[<Params(TestParam.A)>] `works fine. Looks like it converts values to int if there is more that one value. In C# everything works good

### PR DESCRIPTION
**Pull request by gsomix**
Closes #1262 

I've added new type for enum params, that preserves type information for erasured F# enums in attributes. There is obvious code duplication, but that's for reason to keep code changes small and local. We can remove it after F# compiler is fixed. ;)

- [x] Fix F# benchmarks compilation with enum params
- [x] Fix enum values names in Summary
- [x] Write tests for this case

See also:
https://github.com/dotnet/fsharp/issues/995

Happy #hacktoberfest!

### CODE REVIEW

**Comment by gsomix** [comment]
I'd like to write proper tests for this case, but it doesn't clear how to run F# integration "test suite". Could you help me please? @adamsitnik @AndreyAkinshin Thanks!

**Comment by gsomix** [comment]
@isaevdan Review please!

**Comment by gsomix** [comment]
Done.

**Comment by gsomix** [comment]
Yey, green! Err, ready to review. :)

**Comment by isaevdan** [comment]
I see this is still open. In case if it is waiting for me, I`m still fine with implementation :)

**Comment by gsomix** [comment]
@adamsitnik @AndreyAkinshin Hey, guys, any chance to get it merged? Thanks!

**Comment by AndreyAkinshin** [comment]
@gsomix thanks for the PR and sorry for the delay.

**Comment by isaevdan** [comment]
Am I correct that this is no available yet in 0.12, and will be in 0.12.1?
Is there any plans when 0.12.1 will be released?

**Comment by AndreyAkinshin** [comment]
@isaevdan yes, the fix will be available in 0.12.1. The new version should be released this week.

**Comment by isaevdan** [comment]
@AndreyAkinshin Great, thanks for update

**Pull request merged**
