### PR TITLE
Added [ParamsAllValues]

### LINKED ISSUE #658: [Params] for enums should include all values by default
I think that with `[Params]` properties whose type is some `enum`, a fairly common situation is that I want all values of that `enum` to be included. It would be nice if doing this didn't require listing all those values in the attribute. I.e., instead of having to write:

```c#
[Params(CurrentCulture, CurrentCultureIgnoreCase, InvariantCulture, InvariantCultureIgnoreCase, Ordinal, OrdinalIgnoreCase)]
public StringComparison StringComparison { get; set; }
```

I could write just:

```c#
[Params]
public StringComparison StringComparison { get; set; }
```

Do you think this would be a useful feature? Would this be considered a breaking change? (If yes, something like `[EnumParams]` could be added instead.)

### PR DESCRIPTION
**Pull request by gsomix**
Closes #658 

- [x] Rebase #664 
- [x] Add approval tests for the feature
- [x] Implement validators
- [x] Add lost documentation

### CODE REVIEW

**Comment by gsomix** [comment]
@adamsitnik @AndreyAkinshin Could you take a look? Thanks!

**Comment by AndreyAkinshin** [comment]
@adamsitnik could you also review this PR?

**Comment by gsomix** [comment]
@adamsitnik Done! I have also refactored `if-else` to pattern matching. Hope now it's way more cleaner.

**Comment by adamsitnik** [comment]
@gsomix great job! thank you!

**Pull request merged**
