### PR TITLE
Improve search experience in the documentation

### PR DESCRIPTION
**Pull request by s-pace**
Resolves and follow up from dotnet/BenchmarkDotNet#1137

cc @AndreyAkinshin 🚀

### CODE REVIEW

**Comment by AndreyAkinshin** [comment]
@s-pace thanks for the PR! It looks great!

Could you please update the algolia index based on existed sitemap? Currently, I still can't find my favorite articles via the new search (e.g., the "Orderers" search term still gives me only API pages).
I will be happy to merge it to master, but it has to correctly find pages.

**Comment by s-pace** [comment]
👋 @AndreyAkinshin 

Thank you for the feedback. I have forgot to link the final version of the website with this PR https://benchmarkdotnet-docsearch.surge.sh/

I have updated your configuration with your feedback. If you search for Orderers sample you will see that we do index it. I still boost the article pages now https://github.com/algolia/docsearch-configs/commit/3cdb833bd2bb111fda1827cd7542798dbc0d518a

**Comment by s-pace** [comment]
@AndreyAkinshin Let us know if you need anything, we can provide you some access on the search analytics so that you improve the doc accordingly

**Comment by AndreyAkinshin** [comment]
@s-pace sorry for the late response, I was pretty busy lately. Finally, I have some time for BenchmarkDotNet!

I tried https://benchmarkdotnet-docsearch.surge.sh/ but I'm still not happy. Indeed, the `orderers sample` search request find some orderer-specific samples. However, the `orderers` search requests shows API references only:
image
The most important part in the BenchmarkDotNet documentation is pages in the "Articles" section. Currently, it's possible to find these pages (it takes a lot of time, but it's possible):
image

Could we include "Articles" in the search index as well?
The https://benchmarkdotnet.org/sitemap.xml file contains references to all the article pages:
image

**Comment by s-pace** [comment]
👋 @AndreyAkinshin,

Thank you for the complete details.

We were already crawling these "/articles/" pages. However, the default UI of DocSearch only display the top 5 most ranked results. We can [change it if needed (by adding `hitsPerPage` from the JS snippet)](https://community.algolia.com/docsearch/behavior.html#algoliaoptions).

For the query `Orderers`, the result related to a "/articles" pages was too far in the matching list, this is why it was not displayed.

I have updated [the ranking formula of this DocSearch index](https://github.com/algolia/docsearch-configs/commit/715bebaa32614f8dc8f5570fd12ee816a0b7f308) to always boost results having an `lvlX` attribute containing at least one word of the query. This solves the issue we were struggling with. This is live and you [can try it out](https://benchmarkdotnet-docsearch.surge.sh/).

Let us know if you need anything else

**Comment by AndreyAkinshin** [comment]
@s-pace, now it's better, thanks!
One more question about the ranking: could we use the priority from `sitemap.xml`? Currently, I have the following situation:
image
As you can see, the "Orderers" page is shown on the 5th place. I want to move it to the first position using the priority values (it would be nice to control it on the BenchmarkDotNet side without any changes in the DocSearch index).

**Comment by s-pace** [comment]
No problem @AndreyAkinshin 

This feature to add a `page_rank` depending on the sitemap is not available. It will not fix the current issue since both results are coming from the same page actually.

I have [updated your configuration](https://github.com/algolia/docsearch-configs/commit/030cd41cd178e171677d23b0203cbef32cc12fca) to address this problem and boost hit that are higher in the page. It is [already live](https://docsearch-benchmarkdotnet.netlify.com/) and you can let us know if it suits your need :)

**Comment by AndreyAkinshin** [comment]
@s-pace, now it works great, thanks! I will deploy it to benchmarkdotnet.org as soon as v0.11.6 is released.

**Pull request merged**
