### PR TITLE
simplify the reported Full .NET Framework version, fixes 1111

### PR DESCRIPTION
**Pull request by adamsitnik**
@AndreyAkinshin this is my proposal for #1111 

It looks like `Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.FrameworkDescription` returns exactly what we need. 

I decided to remove:

- the SDK version: it was confusing, we don't run the benchmarks against installed SDK but always against latest .NET installed on the machine. Also, as you have noticed the SDK does not need to be installed to run a .NET app
- `System.Environment.Version` - this version number is confusing (even for people who work on .NET Team for 10+ years) because it requires one additional translation to map it to the .NET Framework Version
- `JitModule` version because it returns the same version as `Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.FrameworkDescription` (duplication)

```cmd
dotnet run -c Release --info
```

Was:

```log
  [Host] : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3324.0
```

Is:

```log
  [Host] : .NET Framework 4.7.3324.0, 64bit RyuJIT
```

### CODE REVIEW

**Comment by AndreyAkinshin** [comment]
In general, I like the idea of simplification in this place. However, I think that ".NET Framework 4.7.3324.0" also looks confusing. People know that there is .NET Framework 4.7, 4.7.1, and 4.7.2. In this context, "4.7.3324.0" looks strange. Can we do something with it?

P.S. Please, don't merge it until I approve this PR. I want to make sure that it looks great before we get these changes in master.

**Comment by adamsitnik** [comment]
> Can we do something with it?

We would have to map the version number reported by .NET Framework to the simplified version. 
I don't think it's worth it. 

Also, I am not sure if my box does not have any internal MS-only preview version of .NET Framework installed. What numbers do you get on your box?

**Comment by billwert** [comment]
".NET Framework 4.7.3324.0" is nice because it represents the servicing release that the user has installed. It has been very useful to me to have it. Keeping the string to this would be great:
```
[Host] : .NET Framework 4.7.2 (4.7.3324.0), 64bit RyuJIT
```

I think keeping the rough branding of 4.7.2 or 4.8 in the string is also useful. We talk about releases in those terms, and our [tools](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/application-compatibility) for determining what quirks are enabled in a given release use those terms. My $0.02.

**Comment by adamsitnik** [comment]
@billwert thank you for your input! Now we got 2:1 for the mapping vs no mapping so I added it ;)

sample results now:

```cs
BenchmarkDotNet=v0.11.4.20190520-develop, OS=Windows 10.0.17763.437 (1809/October2018Update/Redstone5)
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
  [Host] : .NET Framework 4.7.2 (4.7.3362.0), 64bit RyuJIT
  Dry    : .NET Framework 4.7.2 (4.7.3362.0), 64bit RyuJIT
```

@AndreyAkinshin could you please take a look at this PR again?

btw I also added .NET 4.8 to the list of known .NET Runtimes

**Pull request merged**
